In [18]:
import numpy as np
from scipy.stats import binom

## Call Payoff Function
def callPayoff(spot, strike):
    return np.maximum(spot - strike, 0.0)

## Put Payoff Function
def putPayoff(spot, strike):
    return np.maximum(strike - spot, 0.0)


In [56]:
def euroBinomPricerRecursiveMatrix(S, K, r, v, q, T, n, payoff, verbose = True):
    nodes = n  + 1
    h = T / n
    #u = np.exp((r - q) * h + v * np.sqrt(h))
    u = 1.3
    #d = np.exp((r - q) * h - v * np.sqrt(h))
    d = 0.8
    pu = (np.exp((r - q) * h) - d) / (u - d)
    pd = 1.0 - pu
    disc = np.exp(-r * h)
    
    
    ## Arrays to store the spot prices and option values
    Ct = np.zeros((nodes, n+1))
    St = np.zeros((nodes, n+1))
    Dt = np.zeros((nodes, n+1))
    Bt = np.zeros((nodes, n+1))
    
    for i in range(nodes):
        St[i, n] = S * (u**(n-i)) * (d**i)
        Ct[i, n] = payoff(St[i, n], K)
    

    for t in range((n-1), -1, -1):
        for j in range(t+1):
            St[j, t] = St[j, t+1] / u
            Ct[j, t] = disc * ((pu * Ct[j, t+1]) + (pd * Ct[j+1, t+1]))
            Dt[j, t] = np.exp(-q * h) * (Ct[j, t+1] - Ct[j+1, t+1]) / (St[j, t] * (u - d))
            Bt[j, t] = np.exp(-r * h) * (((u * Ct[j + 1, t+1]) - (d * Ct[j, t+ 1]))/(u - d))
        
    if verbose:
        print(np.around(St, 3))
        print("\n")
        print(np.around(Ct, 3))
        print("\n")
        print(np.around(Dt, 3))
        print("\n")
        print(np.around(Bt, 3))          
            
    return Ct[0,0]

In [57]:
#Problem 1

S = 100
K = 105
v = 0.3
r = 0.08
T = 0.5
q = 0.0
n = 1

callPrc = euroBinomPricerRecursiveMatrix(S, K, r, v, q, T, n, callPayoff, verbose = True)
callPrc

[[100. 130.]
 [  0.  80.]]


[[11.568 25.   ]
 [ 0.     0.   ]]


[[0.5 0. ]
 [0.  0. ]]


[[-38.432   0.   ]
 [  0.      0.   ]]


11.568422433907068

In [58]:
#Problem 1

S = 100
K = 105
v = 0.3
r = 0.08
T = 0.5
q = 0.0
n = 1

putPrc = euroBinomPricerRecursiveMatrix(S, K, r, v, q, T, n, putPayoff, verbose = True)
putPrc

[[100. 130.]
 [  0.  80.]]


[[12.451  0.   ]
 [ 0.    25.   ]]


[[-0.5  0. ]
 [ 0.   0. ]]


[[62.451  0.   ]
 [ 0.     0.   ]]


12.45131354490101

In [60]:
# Problem 1
#a. The premium for the European call is ~ $11.57, with a Delta of 0.5, 
#and a Beta of -38.432

#b. The premium for the European put is ~$12.45, with a Delta of -0.5,
#and a Beta of 62.451

In [66]:
#Problem 2

S = 100
K = 95
v = 0.3
r = 0.08
T = 0.5
q = 0.0
n = 1

putPrc = euroBinomPricerRecursiveMatrix(S, K, r, v, q, T, n, putPayoff, verbose = True)
putPrc

[[100. 130.]
 [  0.  80.]]


[[ 7.471  0.   ]
 [ 0.    15.   ]]


[[-0.3  0. ]
 [ 0.   0. ]]


[[37.471  0.   ]
 [ 0.     0.   ]]


7.470788126940606

In [68]:
callPrc

16.195791407469894

In [72]:
barbitrage = 17-callPrc
print(barbitrage)

0.8042085925301059


In [73]:
carbitrage = callPrc-15.5
print(carbitrage)

0.6957914074698941


In [71]:
#Problem 2
#a. The price of the European put is $7.471
#b. Short the call at price $17 then our arbitrage would be ~ 80 cents. 
#c. Long the call at price $15.50 our arbitrage would be ~  70 cents.

In [80]:
#Problem 3

S = 100
K = 95
v = 0.3
r = 0.08
T = 1
q = 0.0
n = 2

callPrc = euroBinomPricerRecursiveMatrix(S, K, r, v, q, T, n, callPayoff, verbose = True)
callPrc


[[100. 130. 169.]
 [  0.  80. 104.]
 [  0.   0.  64.]]


[[19.994 38.725 74.   ]
 [ 0.     4.165  9.   ]
 [ 0.     0.     0.   ]]


[[0.691 1.    0.   ]
 [0.    0.225 0.   ]
 [0.    0.    0.   ]]


[[-49.127 -91.275   0.   ]
 [  0.    -13.835   0.   ]
 [  0.      0.      0.   ]]


19.993693459343987

In [ ]:
#Problem 3

#The premium for the fu is $38.725, Delta is 1, and the Beta is -91.275
#The premium for fd it is $4.165, Delta is 0.225, and the Beta is -13.835
#The premium for the call is $19.94, Delta is 0.691, 
#and the Beta is -49.127 


In [96]:
#Problem 4

S = 130
K = 95
v = 0.3
r = 0.08
T = 1
q = 0.0
n = 3

callPrc = euroBinomPricerRecursiveMatrix(S, K, r, v, q, T, n, callPayoff, verbose = True)
callPrc

[[130.    158.762 193.887 236.784]
 [  0.    112.28  137.122 167.459]
 [  0.      0.     96.975 118.431]
 [  0.      0.      0.     83.757]]


[[ 43.967  68.696 101.387 141.784]
 [  0.     25.359  44.621  72.459]
 [  0.      0.     10.422  23.431]
 [  0.      0.      0.      0.   ]]


[[0.932 1.    1.    0.   ]
 [0.    0.852 1.    0.   ]
 [0.    0.    0.676 0.   ]
 [0.    0.    0.    0.   ]]


[[-77.237 -90.066 -92.5     0.   ]
 [  0.    -70.29  -92.5     0.   ]
 [  0.      0.    -55.109   0.   ]
 [  0.      0.      0.      0.   ]]


43.96737396964083

In [79]:
#Problem 4
#80 = 0.485
#90 = 0.609
#110 = 0.828
#120 = 0.885
#130 = 0.932

#Delta increases at a decreasing rate as S increase. 


In [82]:
#Problem 5

def euroBinomPricerRecursiveMatrix(S, K, r, v, q, T, n, payoff, verbose = True):
    nodes = n  + 1
    h = T / n
    u = np.exp((r - q) * h + v * np.sqrt(h))
    #u = 1.3
    d = np.exp((r - q) * h - v * np.sqrt(h))
    #d = 0.8
    pu = (np.exp((r - q) * h) - d) / (u - d)
    pd = 1.0 - pu
    disc = np.exp(-r * h)
    
    
    ## Arrays to store the spot prices and option values
    Ct = np.zeros((nodes, n+1))
    St = np.zeros((nodes, n+1))
    Dt = np.zeros((nodes, n+1))
    Bt = np.zeros((nodes, n+1))
    
    for i in range(nodes):
        St[i, n] = S * (u**(n-i)) * (d**i)
        Ct[i, n] = payoff(St[i, n], K)
    

    for t in range((n-1), -1, -1):
        for j in range(t+1):
            St[j, t] = St[j, t+1] / u
            Ct[j, t] = disc * ((pu * Ct[j, t+1]) + (pd * Ct[j+1, t+1]))
            Dt[j, t] = np.exp(-q * h) * (Ct[j, t+1] - Ct[j+1, t+1]) / (St[j, t] * (u - d))
            Bt[j, t] = np.exp(-r * h) * (((u * Ct[j + 1, t+1]) - (d * Ct[j, t+ 1]))/(u - d))
        
    if verbose:
        print(np.around(St, 3))
        print("\n")
        print(np.around(Ct, 3))
        print("\n")
        print(np.around(Dt, 3))
        print("\n")
        print(np.around(Bt, 3))          
            
    return Ct[0,0]

In [ ]:
#Problem 5

def euroBinomPricerRecursiveMatrix1(S, K, r, v, q, T, n, payoff, verbose = True):
    nodes = n  + 1
    h = T / n
    u = np.exp((r - q) * h + v * np.sqrt(h))
    #u = 1.3
    d = np.exp((r - q) * h - v * np.sqrt(h))
    #d = 0.8
    pu = (np.exp((r - q) * h) - d) / (u - d)
    pd = 1.0 - pu
    disc = np.exp(-r * h)
    
    
    ## Arrays to store the spot prices and option values
    Ct = np.zeros((nodes, n+1))
    St = np.zeros((nodes, n+1))
    Dt = np.zeros((nodes, n+1))
    Bt = np.zeros((nodes, n+1))
    
    for i in range(nodes):
        St[i, n] = S * (u**(n-i)) * (d**i)
        Ct[i, n] = payoff(St[i, n], K)
    

    for t in range((n-1), -1, -1):
        for j in range(t+1):
            St[j, t] = St[j, t+1] / u
            Ct[j, t] = disc * ((pu * Ct[j, t+1]) + (pd * Ct[j+1, t+1]))
            Dt[j, t] = np.exp(-q * h) * (Ct[j, t+1] - Ct[j+1, t+1]) / (St[j, t] * (u - d))
            Bt[j, t] = np.exp(-r * h) * (((u * Ct[j + 1, t+1]) - (d * Ct[j, t+ 1]))/(u - d))
        
    if verbose:
        print(np.around(St, 3))
        print("\n")
        print(np.around(Ct, 3))
        print("\n")
        print(np.around(Dt, 3))
        print("\n")
        print(np.around(Bt, 3))          
            
    return Ct[0,0]

In [90]:
# Problem 5

S = 100
K = 95
v = 0.3
r = 0.08
T = 1
q = 0.0
n = 3

callPrc = euroBinomPricerRecursiveMatrix(S, K, r, v, q, T, n, callPayoff, verbose = True)
callPrc

[[100.    122.125 149.144 182.142]
 [  0.     86.369 105.478 128.815]
 [  0.      0.     74.596  91.101]
 [  0.      0.      0.     64.428]]


[[18.283 33.149 56.644 87.142]
 [ 0.     6.69  15.04  33.815]
 [ 0.     0.     0.     0.   ]
 [ 0.     0.     0.     0.   ]]


[[0.74  0.953 1.    0.   ]
 [0.    0.487 0.897 0.   ]
 [0.    0.    0.    0.   ]
 [0.    0.    0.    0.   ]]


[[-55.719 -83.207 -92.5     0.   ]
 [  0.    -35.375 -79.532   0.   ]
 [  0.      0.      0.      0.   ]
 [  0.      0.      0.      0.   ]]


18.28255220737056

In [91]:
#Problem 5

S = 100
K = 95
v = 0.3
r = 0.08
T = 1
q = 0.0
n = 3

putPrc = euroBinomPricerRecursiveMatrix(S, K, r, v, q, T, n, putPayoff, verbose = True)
putPrc

[[100.    122.125 149.144 182.142]
 [  0.     86.369 105.478 128.815]
 [  0.      0.     74.596  91.101]
 [  0.      0.      0.     64.428]]


[[ 5.979  1.091  0.     0.   ]
 [ 0.    10.387  2.062  0.   ]
 [ 0.     0.    17.904  3.899]
 [ 0.     0.     0.    30.572]]


[[-0.26  -0.047  0.     0.   ]
 [ 0.    -0.513 -0.103  0.   ]
 [ 0.     0.    -1.     0.   ]
 [ 0.     0.     0.     0.   ]]


[[31.977  6.859  0.     0.   ]
 [ 0.    54.691 12.968  0.   ]
 [ 0.     0.    92.5    0.   ]
 [ 0.     0.     0.     0.   ]]


5.97860511410097

In [92]:
#problem 5 b
(callPrcputPrc) = callPrc-putPrc
print(callPrcputPrc)

12.30394709326959


In [97]:
#problem 5 c
parity = 100 - (95*np.exp(-.08*1))
print(parity)

12.3039470932696


In [113]:
def euroBinomPricerRecursive(S, K, r, v, q, T, n, payoff, verbose = False):
    nodes = n  + 1
    h = T / n
    u = np.exp((r - q) * h + v * np.sqrt(h))
    d = np.exp((r - q) * h - v * np.sqrt(h))
    pu = (np.exp((r - q) * h) - d) / (u - d)
    pd = 1.0 - pu
    disc = np.exp(-r * h)
   
   
   ## Arrays to store the spot prices and option values
    Ct = np.empty(nodes)
    St = np.empty(nodes)
   
    for i in range(nodes):
        St[i] = S * (u ** (n - i)) * (d ** i)
        Ct[i] = payoff(St[i], K)
   
    if verbose:
        print(Ct)
       
    for t in range((n - 1), -1, -1):
        for j in range(t+1):
            Ct[j] = disc * (pu * Ct[j] + pd * Ct[j+1])
            St[j] = St[j] / u
            Ct[j] = np.maximum(Ct[j], K - St[j])
        
    print(Ct)
           
    return Ct[0]



In [114]:
def euroBinomPricerRecursiveMatrix(S, K, r, v, q, T, n, payoff, verbose = False):
    nodes = n  + 1
    h = T / n
    u = np.exp((r - q) * h + v * np.sqrt(h))
    d = np.exp((r - q) * h - v * np.sqrt(h))
    pu = (np.exp((r - q) * h) - d) / (u - d)
    pd = 1.0 - pu
    disc = np.exp(-r * h)
   
   ## Arrays to store the spot prices and option values
    Ct = np.zeros((nodes, n+1))
    St = np.zeros((nodes, n+1))
    Dt = np.zeros((nodes, n+1))
   
    for i in range(nodes):
        St[i, n] = S * (u**(n-i)) * (d**i)
        Ct[i, n] = payoff(St[i, n], K)
   

    for t in range((n-1), -1, -1):
        for j in range(t+1):
            St[j, t] = St[j, t+1] / u
            Ct[j, t] = disc * ((pu * Ct[j, t+1]) + (pd * Ct[j+1, t+1]))
            Dt[j, t] = np.exp(-q * h) * (Ct[j, t+1] - Ct[j+1, t+1]) / (St[j, t] * (u - d))
            
    return Ct[0,0]

In [115]:
S = 100
K = 95
r = 0.08
v = 0.30
q = 0.0
T = 1
n = 3

In [116]:
callPrcA = euroBinomPricerRecursive(S, K, r, v, q, T, n, callPayoff,  verbose = False)
callPrcE = euroBinomPricerRecursiveMatrix(S, K, r, v, q, T, n, callPayoff,  verbose = False)
putPrcA = euroBinomPricerRecursive(S, K, r, v, q, T, n, putPayoff,  verbose = False)
putPrcE = euroBinomPricerRecursiveMatrix(S, K, r, v, q, T, n, putPayoff,  verbose = False)

print(f"The European Call Premium: {callPrcE : 0.3f} The American call is {callPrcE : 0.3f}")
print(f"The European Put Premium: {putPrcE : 0.3f} The American put is {putPrcA : 0.3f}")


[23.99012609 17.48114202 20.40351726  0.        ]
[ 6.67790123 11.7087201  20.40351726 30.57157332]
The European Call Premium:  18.283 The American call is  18.283
The European Put Premium:  5.979 The American put is  6.678


In [95]:
#Problem 5
#a. The premium for an American call option is $18.28. 
#There is no early excersize. 
#b.The European call option premium is $5.98. 
#The difference between the two is: $12.30395
#c The price of the European put is $5.98. 
#The put-call parity holds becasue the 
#  callPrc-putPrc = 100 - (95*np.exp(-.08*1)), 
#Which means that $12.30 = $12.30. 
#Therefore, we can conclude that the put-call parity holds. 
#d. The American put is $6.678 and the European up is $5.979. 
#The American has early excersize on. That's why it's bigger. 

In [120]:
#Problem 6
S = 40
K = 40
r = 0.08
v = 0.30
q = 0.0
T = 0.5
n = 3
h = T/n

u6 = np.exp((r - q) * h + v * np.sqrt(h))
d6 = np.exp((r - q) * h - v * np.sqrt(h))

In [121]:
callPrcA = euroBinomPricerRecursive(S, K, r, v, q, T, n, callPayoff,  verbose = False)
callPrcE = euroBinomPricerRecursiveMatrix(S, K, r, v, q, T, n, callPayoff,  verbose = False)
putPrcA = euroBinomPricerRecursive(S, K, r, v, q, T, n, putPayoff,  verbose = False)
putPrcE = euroBinomPricerRecursiveMatrix(S, K, r, v, q, T, n, putPayoff,  verbose = False)

print(f"The European Call Premium: {callPrcE : 0.3f} The American call is {callPrcE : 0.3f}")
print(f"The European Put Premium: {putPrcE : 0.3f} The American put is {putPrcA : 0.3f}")
print(u6)
print(d6)


[6.52754713 5.6208478  7.84406148 0.        ]
[ 2.95422756  4.8747172   7.84406148 11.16886174]
The European Call Premium:  4.377 The American call is  4.377
The European Put Premium:  2.809 The American put is  2.954
1.1454617381452392
0.8966038495199921


In [ ]:
#Problem 6
#a. u is ~ 1.1455 and d is ~ 0.8966.
#b. The American put premia is $2.954 and the call is $4.377
#The European put premia is $4.377 and the call is $2.809
